version: "3.8"
services:
  web:
    build: ./app
    image: 696585771625.dkr.ecr.us-west-1.amazonaws.com/books:books_web
    command: gunicorn ncbooks.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_books_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=ncbooks.c8ibelumn7tx.us-west-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-13-57-164-175.us-west-1.compute.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 696585771625.dkr.ecr.us-west-1.amazonaws.com/books:books_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: